name = "thaliak-api"
main = "build/worker/shim.mjs"
compatibility_date = "2023-07-24"

kv_namespaces = [
  { binding = "thaliak-data", preview_id = "57c6c87beccb45e0a8dbf6557ad9e334", id = "b2fbfd7f0f35418b8cac2c5e599047d4" }
]

[build]
command = "cargo install -q worker-build && worker-build --release"

# Local development
[env.local]
kv_namespaces = [
  { binding = "thaliak-data", preview_id = "LOCAL", id = "LOCAL" }
]

[env.local.build]
# Build with the `debug` feature enabled, but in release mode,
# to ensure that the build is optimized as it will be in production.
command = "cargo install -q worker-build && worker-build --release --features debug"
