name: docker build Thaliak.AdminCli
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/**'
      - 'Thaliak.Common.Database/**'
      - 'Thaliak.Analysis.Engine/**'
      - 'Thaliak.Common.Messages/**'
      - 'Thaliak.AdminCli/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Thaliak.AdminCli/Dockerfile
          push: true
          tags: ghcr.io/crystallinetools/thaliak-admin-cli:latest

