name: "build & deploy: poller (v1)"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "v1/Thaliak.Common.Database/**"
      - "v1/Thaliak.Service.Poller/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Thaliak.Service.Poller/Dockerfile
          push: true
          tags: ghcr.io/crystallinetools/thaliak-poller:latest
      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: "${{ secrets.REMOTE_HOST }}"
          port: 22
          username: "${{ secrets.REMOTE_USER }}"
          key: "${{ secrets.REMOTE_SSH_KEY }}"
          script: deploy poller
