name: ci
on:
  push:
    branches:
      # todo: adjust this to `main` once v2 is released
      - two
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/bake-action@v3
        with:
          files: docker-bake.hcl
          push: true
